#!/bin/sh
#

if ! grep -q opentdp /etc/frp/frpc.ini; then
    echo "Failed to join OpenTDP Blackbox"
    sleep 60
    kill 1
fi

# start services

frpc -c /etc/frp/frpc.ini &
blackbox_exporter --config.file=/etc/prometheus/blackbox.yml &
