#!/bin/sh
#

OS_ARCH=""
case $(uname -m) in
  "i386")     OS_ARCH="386";;
  "i686")     OS_ARCH="386";;
  "x86_64")   OS_ARCH="amd64";;
  "armv7l")   OS_ARCH="armv7";;
  "aarch64")  OS_ARCH="arm64";;
  "mips")     OS_ARCH="mips";;
  "mipsel")   OS_ARCH="mipsle";;
  "mips64")   OS_ARCH="mips64";;
  "mips64el") OS_ARCH="mips64le";;
  "ppc64")    OS_ARCH="ppc64";;
  "ppc64le")  OS_ARCH="ppc64le";;
  "s390x")    OS_ARCH="s390x";;
esac

gunzip /ifs/tdp-blackbox-linux-$OS_ARCH.gz -c >/usr/local/bin/tdp-blackbox
cp -a /ifs/tdp-server /usr/local/bin/

chmod +x /usr/local/bin/*

rm -rf /ifs
