#!/bin/sh -e
#

tdp_arch() {

  local arch=$(uname -m)

  case $arch in
    "i386")     arch="386";;
    "i686")     arch="386";;
    "x86_64")   arch="amd64";;
    "armv7l")   arch="armv7";;
    "aarch64")  arch="arm64";;
  esac

  echo $arch

}

tdp_release() {

    releases_url=https://api.github.com/repos/opentdp/$1/releases/latest
    binary_url=`wget -qO- $releases_url | grep releases/download | cut -f4 -d "\""`

    for url in $binary_url; do
        echo $url | grep linux-$(tdp_arch)
    done

}

wget -O tdp-blackbox.gz $(tdp_release blackbox)
gunzip tdp-blackbox.gz -c >/usr/local/bin/tdp-blackbox

cp -a /ifs/tdp-server /usr/local/bin/
chmod +x /usr/local/bin/*

rm -rf /ifs
