name: TDP Blackbox Builder

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build client binary
        run: |
          cd ./client && sh build.sh

      - name: Create github release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ./client/RELEASE.md
          draft: false
          prerelease: false
          files: |
            ./client/build/*
